name: Telegram Notification on Push

on:
  push:
    # branches: [ main, develop ] # This line is now a comment.
    # The workflow will now trigger on push to ALL branches.

jobs:
  notify_telegram:
    # Only run this job if the previous job succeeded (or if this is the first job)
    runs-on: ubuntu-latest

    steps:
      - name: Send notification on successful push
        uses: appleboy/telegram-action@master
        with:
          # Required: Your bot's authorization token (stored as a secret)
          token: ${{ secrets.TELEGRAM_TOKEN }}
          
          # Required: Unique identifier for the target chat/channel (stored as a secret)
          to: ${{ secrets.TELEGRAM_TO }} 
          
          # Optional: The message to send
          message: |
            ✅ SUCCESSFUL PUSH to ${{ github.ref_name }}
            
            👤 Actor: ${{ github.actor }}
            🔗 Commit: ${{ github.sha }}
            
            Repo: ${{ github.repository }}
            See workflow run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            
          # Optional: Use Markdown for rich formatting
          format: markdown
